"""
api/export.py — POST /api/export/zip  |  POST /api/export/pdf
Phase 5: Export scaffold as ZIP, PRD as styled PDF
"""
import io, json, zipfile, os, sys
from datetime import datetime
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))


# ══ ZIP EXPORT ════════════════════════════════════════════════
def handle_export_zip(body: dict) -> tuple[bytes, str]:
    """
    Receives: { name, files: [{type, path, content}] }
    Returns:  (zip_bytes, filename)
    """
    name  = body.get('name', 'forge-project').strip() or 'forge-project'
    files = body.get('files', [])

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, 'w', zipfile.ZIP_DEFLATED) as zf:
        added = set()
        for f in files:
            ftype   = f.get('type', 'file')
            path    = f.get('path', '').lstrip('/')
            content = f.get('content', '')

            if not path or path in added:
                continue
            added.add(path)

            if ftype == 'dir':
                # ZIP directories need trailing slash
                zf.mkdir(f'{name}/{path}' if not path.endswith('/') else f'{name}/{path}')
            else:
                zf.writestr(f'{name}/{path}', content or '')

        # Always add a .forge metadata file
        meta = {
            'project':   name,
            'exported':  datetime.utcnow().isoformat() + 'Z',
            'files':     len([f for f in files if f.get('type') == 'file']),
            'generator': 'FORGE v1.0',
        }
        zf.writestr(f'{name}/.forge', json.dumps(meta, indent=2))

    buf.seek(0)
    filename = f'{name}-scaffold.zip'
    return buf.read(), filename


# ══ PDF EXPORT ════════════════════════════════════════════════
def handle_export_pdf(body: dict) -> tuple[bytes, str]:
    """
    Receives: { name, sections: {overview, features, stories, tech, ...} }
    Returns:  (pdf_bytes, filename)
    """
    name     = body.get('name', 'Project').strip() or 'Project'
    sections = body.get('sections', {})

    pdf_bytes = _build_pdf(name, sections)
    filename  = f'{name.lower().replace(" ","-")}-prd.pdf'
    return pdf_bytes, filename


def _build_pdf(name: str, sections: dict) -> bytes:
    """Build PDF using reportlab if available, else plain HTML fallback."""
    try:
        return _pdf_reportlab(name, sections)
    except ImportError:
        return _pdf_html_fallback(name, sections)


def _pdf_reportlab(name: str, sections: dict) -> bytes:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.lib import colors
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, HRFlowable,
        Table, TableStyle, KeepTogether
    )
    from reportlab.lib.enums import TA_LEFT, TA_CENTER

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=2.5*cm, rightMargin=2.5*cm,
        topMargin=2.5*cm, bottomMargin=2.5*cm,
    )

    # ── Colour palette ──────────────────────────────────────
    INDIGO  = colors.HexColor('#6366f1')
    DARK    = colors.HexColor('#0f0f1a')
    SURFACE = colors.HexColor('#1e1e2e')
    TEXT    = colors.HexColor('#e2e4f0')
    MUTED   = colors.HexColor('#9294a8')
    GREEN   = colors.HexColor('#34d399')
    WHITE   = colors.white

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle('ForgeTitle',
        fontName='Helvetica-Bold', fontSize=26,
        textColor=INDIGO, spaceAfter=6, leading=32)

    sub_style = ParagraphStyle('ForgeSub',
        fontName='Helvetica', fontSize=11,
        textColor=MUTED, spaceAfter=4, leading=16)

    meta_style = ParagraphStyle('ForgeMeta',
        fontName='Helvetica', fontSize=9,
        textColor=MUTED, spaceAfter=2)

    sec_title_style = ParagraphStyle('ForgeSecTitle',
        fontName='Helvetica-Bold', fontSize=13,
        textColor=INDIGO, spaceBefore=18, spaceAfter=8, leading=18)

    body_style = ParagraphStyle('ForgeBody',
        fontName='Helvetica', fontSize=10,
        textColor=colors.HexColor('#4a4a6a'),
        spaceAfter=6, leading=16)

    bullet_style = ParagraphStyle('ForgeBullet',
        fontName='Helvetica', fontSize=10,
        textColor=colors.HexColor('#4a4a6a'),
        spaceAfter=4, leading=15,
        leftIndent=16, bulletIndent=6)

    story = []

    # ── Header block ────────────────────────────────────────
    story.append(Paragraph(name, title_style))
    story.append(Paragraph('Product Requirements Document', sub_style))
    story.append(Paragraph(
        f'Generated by FORGE v1.0 &nbsp;·&nbsp; {datetime.utcnow().strftime("%B %d, %Y")}',
        meta_style))
    story.append(Spacer(1, 0.3*cm))
    story.append(HRFlowable(width='100%', thickness=2, color=INDIGO, spaceAfter=20))

    # ── Sections ────────────────────────────────────────────
    SECTION_LABELS = {
        'overview':  'Overview',
        'features':  'Core Features',
        'stories':   'User Stories',
        'tech':      'Technical Requirements',
        'api':       'API Specification',
        'timeline':  'Timeline & Milestones',
    }

    for key, label in SECTION_LABELS.items():
        content = sections.get(key, '')
        if not content:
            continue

        sec_elements = []
        sec_elements.append(Paragraph(label, sec_title_style))
        sec_elements.append(HRFlowable(width='100%', thickness=0.5,
                                        color=SURFACE, spaceAfter=8))

        # Parse content into lines
        text = str(content).strip()
        # Remove wrapping list brackets if present
        if text.startswith('[') and text.endswith(']'):
            try:
                import ast
                items = ast.literal_eval(text)
                for item in items:
                    sec_elements.append(Paragraph(
                        f'• {str(item).strip()}', bullet_style))
            except Exception:
                sec_elements.append(Paragraph(text, body_style))
        elif text.startswith('{'):
            try:
                import ast
                obj = ast.literal_eval(text)
                for k, v in obj.items():
                    sec_elements.append(Paragraph(
                        f'<b>{k.replace("_"," ").title()}:</b> {v}', body_style))
            except Exception:
                sec_elements.append(Paragraph(text, body_style))
        else:
            # Split on bullet markers and newlines
            lines = text.replace('• ', '\n• ').split('\n')
            for line in lines:
                line = line.strip()
                if not line:
                    continue
                if line.startswith('• ') or line.startswith('- ') or line.startswith('* '):
                    sec_elements.append(Paragraph(line, bullet_style))
                else:
                    sec_elements.append(Paragraph(line, body_style))

        story.append(KeepTogether(sec_elements))

    # ── Footer ──────────────────────────────────────────────
    story.append(Spacer(1, 1*cm))
    story.append(HRFlowable(width='100%', thickness=0.5, color=SURFACE))
    story.append(Spacer(1, 0.2*cm))
    story.append(Paragraph(
        f'Confidential &nbsp;·&nbsp; {name} &nbsp;·&nbsp; FORGE AI Project Launch Suite',
        ParagraphStyle('footer', fontName='Helvetica', fontSize=8, textColor=MUTED,
                       alignment=TA_CENTER)))

    doc.build(story)
    buf.seek(0)
    return buf.read()


def _pdf_html_fallback(name: str, sections: dict) -> bytes:
    """
    Fallback: return an HTML file styled like a PDF document.
    Browser can print-to-PDF from this.
    """
    SECTION_LABELS = {
        'overview': 'Overview', 'features': 'Core Features',
        'stories': 'User Stories', 'tech': 'Technical Requirements',
        'api': 'API Specification', 'timeline': 'Timeline',
    }

    secs_html = ''
    for key, label in SECTION_LABELS.items():
        content = sections.get(key, '')
        if not content:
            continue
        text = str(content).strip()
        secs_html += f'<h2>{label}</h2><div class="content">{text}</div>'

    html = f"""<!DOCTYPE html><html><head><meta charset="UTF-8">
<title>{name} — PRD</title>
<style>
  body{{font-family:Georgia,serif;max-width:820px;margin:40px auto;padding:40px;color:#222;line-height:1.7;}}
  h1{{color:#6366f1;font-size:2rem;margin-bottom:4px;}}
  .sub{{color:#888;font-size:0.95rem;margin-bottom:30px;border-bottom:2px solid #6366f1;padding-bottom:16px;}}
  h2{{color:#6366f1;font-size:1.1rem;border-bottom:1px solid #eee;padding-bottom:6px;margin-top:32px;}}
  .content{{color:#444;font-size:0.95rem;white-space:pre-wrap;}}
  .footer{{margin-top:40px;padding-top:12px;border-top:1px solid #eee;color:#aaa;font-size:0.8rem;text-align:center;}}
</style></head><body>
<h1>{name}</h1>
<div class="sub">Product Requirements Document &nbsp;·&nbsp; Generated by FORGE v1.0 &nbsp;·&nbsp; {datetime.utcnow().strftime("%B %d, %Y")}</div>
{secs_html}
<div class="footer">Confidential · {name} · FORGE AI Project Launch Suite</div>
</body></html>"""

    return html.encode('utf-8')