"""api/scaffold.py — POST /api/scaffold
Phase 3: LLM generates real file structure + content.
If GitHub token provided, creates real repo via GitHub API.
"""
import os, sys, json, urllib.request, urllib.error, base64
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
from core import llm, prompts
from core.prompts import get_ci_template


def _parse_json(text: str) -> dict:
    import re
    text = text.strip()
    if text.startswith('```'):
        lines = text.split('\n')
        text = '\n'.join(lines[1:-1] if lines[-1].strip() == '```' else lines[1:])
    text = text.strip()
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    def sanitize_json_strings(s: str) -> str:
        result = []
        in_string = False
        i = 0
        while i < len(s):
            c = s[i]
            if c == '\\' and in_string:
                result.append(c)
                if i + 1 < len(s):
                    result.append(s[i + 1])
                    i += 2
                    continue
            elif c == '"':
                in_string = not in_string
                result.append(c)
            elif in_string:
                if c == '\n':   result.append('\\n')
                elif c == '\r': result.append('\\r')
                elif c == '\t': result.append('\\t')
                elif ord(c) < 32: result.append(f'\\u{ord(c):04x}')
                else: result.append(c)
            else:
                result.append(c)
            i += 1
        return ''.join(result)

    try:
        return json.loads(sanitize_json_strings(text))
    except json.JSONDecodeError:
        pass

    start = text.find('{')
    end   = text.rfind('}')
    if start != -1 and end != -1:
        try:
            return json.loads(sanitize_json_strings(text[start:end+1]))
        except json.JSONDecodeError:
            pass

    raise json.JSONDecodeError('Could not parse LLM scaffold response', text, 0)


def _github_create_repo(token: str, name: str, private: bool = False) -> dict:
    data = json.dumps({
        'name': name, 'private': private,
        'auto_init': False, 'description': 'Generated by FORGE',
    }).encode()
    req = urllib.request.Request(
        'https://api.github.com/user/repos', data=data,
        headers={'Authorization': f'token {token}', 'Accept': 'application/vnd.github+json',
                 'Content-Type': 'application/json', 'X-GitHub-Api-Version': '2022-11-28'},
        method='POST',
    )
    try:
        with urllib.request.urlopen(req, timeout=10) as r:
            return json.loads(r.read())
    except urllib.error.HTTPError as e:
        body = e.read().decode()
        raise RuntimeError(f'GitHub repo creation failed ({e.code}): {body[:200]}')


def _github_push_file(token: str, repo_full: str, path: str, content: str,
                      message: str = 'Initial scaffold by FORGE'):
    encoded = base64.b64encode(content.encode()).decode()
    data = json.dumps({'message': message, 'content': encoded}).encode()
    url = f'https://api.github.com/repos/{repo_full}/contents/{path}'
    req = urllib.request.Request(
        url, data=data,
        headers={'Authorization': f'token {token}', 'Accept': 'application/vnd.github+json',
                 'Content-Type': 'application/json'},
        method='PUT',
    )
    try:
        with urllib.request.urlopen(req, timeout=10) as r:
            return json.loads(r.read())
    except urllib.error.HTTPError as e:
        if e.code == 422:
            return {}
        raise RuntimeError(f'GitHub push failed for {path} ({e.code}): {e.read().decode()[:100]}')


# ---------------------------------------------------------------------------
# SCAFFOLD VALIDATION — normalize LLM output before CI selection
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# MANDATORY SKELETON — guaranteed file structure per project type
# ---------------------------------------------------------------------------

# Python-only mandatory files (content provided by LLM, paths guaranteed by us)
_PYTHON_SKELETON = [
    'main.py', 'models.py', 'routes/api.py',
    'services/core.py', 'tests/test_main.py',
    'requirements.txt', '.env.example',
]

# Fullstack mandatory files — backend + frontend
_FULLSTACK_SKELETON_BACKEND = [
    'main.py', 'models.py', 'routes/api.py',
    'services/core.py', 'tests/test_main.py',
    'requirements.txt', '.env.example',
]
_FULLSTACK_SKELETON_FRONTEND = [
    'frontend/package.json',
    'frontend/public/index.html',
    'frontend/src/App.js',
    'frontend/src/index.js',
]

_FRONTEND_PKG  = '{"name":"frontend","version":"1.0.0","private":true,"scripts":{"start":"react-scripts start","build":"react-scripts build","test":"react-scripts test --passWithNoTests"},"dependencies":{"react":"^18.2.0","react-dom":"^18.2.0","react-scripts":"5.0.1","axios":"^1.4.0"}}'
_FRONTEND_HTML = '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><title>App</title></head><body><div id="root"></div></body></html>'
_FRONTEND_INDEX = "import React from 'react';\nimport ReactDOM from 'react-dom/client';\nimport App from './App';\nconst root = ReactDOM.createRoot(document.getElementById('root'));\nroot.render(<React.StrictMode><App /></React.StrictMode>);"
_FRONTEND_APP   = "import React from 'react';\nfunction App() { return <div><h1>App</h1></div>; }\nexport default App;"

_SKELETON_DEFAULTS = {
    'frontend/package.json':       _FRONTEND_PKG,
    'frontend/public/index.html':  _FRONTEND_HTML,
    'frontend/src/index.js':       _FRONTEND_INDEX,
    'frontend/src/App.js':         _FRONTEND_APP,
}

_BACKEND_DIRS = {'routes/', 'services/', 'tests/', 'api/'}


def _detect_project_type(files: list, stack: list) -> str:
    """
    Determine project type from ACTUAL generated files.
    Returns: 'python', 'node', 'fullstack'
    """
    paths = {f['path'] for f in files if f.get('type') == 'file'}
    has_py = any(p.endswith('.py') for p in paths)

    # Detect any JS/React signal — including misplaced files like app/index.js
    has_js = any(
        p.endswith(('.js', '.jsx', '.tsx', '.ts'))
        and not any(p.startswith(d) for d in _BACKEND_DIRS)
        for p in paths
    )

    # Stack keywords as secondary signal
    stack_lower = ' '.join(s.lower() for s in stack)
    stack_has_react  = any(k in stack_lower for k in {'react', 'vue', 'angular', 'nextjs', 'next.js'})
    stack_has_python = any(k in stack_lower for k in {'fastapi', 'flask', 'django', 'python'})
    stack_has_node   = any(k in stack_lower for k in {'node', 'express', 'node.js', 'express.js'})

    # Fullstack: Python+React OR Node+React (any backend + React frontend)
    has_backend = has_py or stack_has_python or has_js or stack_has_node
    has_frontend = stack_has_react or any('frontend/' in f.get('path','') for f in files if isinstance(f, dict))

    if stack_has_react and (has_py or stack_has_python):
        return 'fullstack'   # Python + React
    if stack_has_react and (has_js or stack_has_node):
        return 'fullstack'   # Node + React
    if has_py or stack_has_python:
        return 'python'
    if has_js or stack_has_node:
        return 'node'
    return 'python'  # safe default


def _validate_scaffold(files: list, stack: list) -> list:
    """
    Enforce mandatory skeleton per project type.
    1. Detect project type from files + stack
    2. Move misplaced frontend JS files → frontend/src/
    3. Guarantee all skeleton files exist (inject defaults if missing)
    LLM-generated content is kept; only missing files are injected.
    """
    project_type = _detect_project_type(files, stack)
    print(f'  [SCAFFOLD] project type: {project_type}')

    if project_type != 'fullstack':
        # Python-only: no frontend normalization needed
        paths = {f['path'] for f in files if f.get('type') == 'file'}
        print(f'  [SCAFFOLD] {project_type}: {len(paths)} files — no normalization needed')
        return files

    # ── FULLSTACK normalization ──────────────────────────────────────────────

    # Step 1: Move any misplaced frontend JS files → frontend/src/
    normalized = []
    for f in files:
        fpath = f.get('path', '')
        if (f.get('type') == 'file'
                and fpath.endswith(('.js', '.jsx', '.tsx', '.css', '.ts'))
                and not fpath.startswith('frontend/')
                and not any(fpath.startswith(d) for d in _BACKEND_DIRS)):
            new_path = 'frontend/src/' + fpath.split('/')[-1]
            print(f'  [SCAFFOLD] moved: {fpath} → {new_path}')
            f = dict(f, path=new_path)
        normalized.append(f)
    files = normalized

    # Step 2: Build path index after normalization
    path_map = {f['path']: f for f in files if f.get('type') == 'file'}

    # Step 3: Guarantee every frontend skeleton file exists
    for skel_path in _FULLSTACK_SKELETON_FRONTEND:
        if skel_path not in path_map:
            default_content = _SKELETON_DEFAULTS.get(skel_path, f'// {skel_path}')
            print(f'  [SCAFFOLD] injecting: {skel_path}')
            files.append({'type': 'file', 'path': skel_path, 'content': default_content})

    print(f'  [SCAFFOLD] fullstack normalized: {len(files)} files total')
    return files





# ---------------------------------------------------------------------------
# Main handler
# ---------------------------------------------------------------------------

def handle_scaffold(body: dict) -> dict:
    name      = body.get('name', 'forge-project').strip() or 'forge-project'
    stack     = body.get('stack', [])
    structure = body.get('structure', 'monorepo')
    prd       = body.get('prd', {})
    idea      = body.get('idea', '')
    gh_token  = body.get('github_token', '')
    private   = body.get('private', False)

    prd_overview = prd.get('overview', '') if isinstance(prd, dict) else ''

    # ── LLM: generate scaffold ──────────────────────────────────────────────
    system, user = prompts.generate_scaffold(idea, stack, structure, prd_overview)
    result = llm.call(prompt=user, system=system, max_tokens=2500)

    try:
        parsed = _parse_json(result['text'])
    except json.JSONDecodeError as e:
        raise RuntimeError(f'LLM returned invalid JSON: {e}')

    files  = parsed.get('files', [])
    readme = parsed.get('readme', '')
    docker = parsed.get('docker_compose', '')

    # ── VALIDATE + NORMALIZE before CI selection ────────────────────────────
    files = _validate_scaffold(files, stack)

    # ── CI template: file-based detection (not stack guessing) ──────────────
    gh_actions = get_ci_template(stack, files)

    # Add README, docker-compose, CI workflow
    extra_files = []
    existing_paths = {f['path'] for f in files}

    if readme and 'README.md' not in existing_paths:
        extra_files.append({'type': 'file', 'path': 'README.md', 'content': readme})
    if docker and 'docker-compose.yml' not in existing_paths:
        extra_files.append({'type': 'file', 'path': 'docker-compose.yml', 'content': docker})
    if gh_actions:
        extra_files.append({'type': 'dir',  'path': '.github/'})
        extra_files.append({'type': 'dir',  'path': '.github/workflows/'})
        extra_files.append({'type': 'file', 'path': '.github/workflows/ci.yml', 'content': gh_actions})

    all_files = files + extra_files
    repo_url  = f'https://github.com/user/{name}'
    pushed    = 0

    # ── GitHub: create repo + push files ────────────────────────────────────
    if gh_token:
        try:
            repo_info = _github_create_repo(gh_token, name, private)
            repo_full = repo_info.get('full_name', f'user/{name}')
            repo_url  = repo_info.get('html_url', repo_url)

            workflow_files = [f for f in all_files if '.github' in f.get('path', '')]
            src_files      = [f for f in all_files if '.github' not in f.get('path', '')]

            src_pushed = 0
            for f in src_files:
                if f['type'] == 'file' and f.get('content', '').strip():
                    _github_push_file(gh_token, repo_full, f['path'], f['content'])
                    print(f'  [GitHub] pushed: {f["path"]}')
                    src_pushed += 1

            wf_pushed = 0
            for f in workflow_files:
                if f['type'] == 'file' and f.get('content', '').strip():
                    _github_push_file(gh_token, repo_full, f['path'], f['content'])
                    print(f'  [GitHub] pushed workflow: {f["path"]}')
                    wf_pushed += 1

            print(f'  [GitHub] repo created/found: {repo_url}')
            print(f'  [GitHub] pushing {src_pushed} files + {wf_pushed} workflow files...')
            pushed = src_pushed + wf_pushed

        except RuntimeError as e:
            return {
                'files':        all_files, 'repo_url': '',
                'pushed':       0,         'github_error': str(e),
                'tokens_used':  result['tokens_used'], 'model': result['model'],
                'provider':     result['provider'],    'latency_ms': result['latency_ms'],
            }

    return {
        'files':       all_files,  'repo_url':    repo_url,
        'pushed':      pushed,     'tokens_used': result['tokens_used'],
        'model':       result['model'], 'provider': result['provider'],
        'latency_ms':  result['latency_ms'],
    }